apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-preload-data-config
  labels:
    name: mysql-data-store
    app: database
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS bookmanagement;
    USE bookmanagement;
    DROP TABLE IF EXISTS books;
    CREATE TABLE books(
     id int NOT NULL AUTO_INCREMENT,
     title varchar(255) NOT NULL,
     author varchar(255) NOT NULL,
     language varchar(255) DEFAULT NULL,
    PRIMARY KEY (id)
    );
    INSERT INTO books(title, author, language) VALUES ('Roots', 'Alex Haley', 'English');
    INSERT INTO books(title, author, language) VALUES ('What If?', 'Randall Munroe', 'English');
    INSERT INTO books(title, author, language) VALUES ('The Path To Power', 'Robert Caro', 'English');
    INSERT INTO books(title, author, language) VALUES ('Little Fires Everywhere', 'Celeste Ng', 'English');
    INSERT INTO books(title, author, language) VALUES ('Under the Radar', 'Robert Young', 'English');
    INSERT INTO books(title, author, language) VALUES ('Deacon King Kong', 'James McBride', 'English');
    INSERT INTO books(title, author, language) VALUES ('Your Inner Fish', 'Neil Shubin', 'English');
    INSERT INTO books(title, author, language) VALUES ('Americanah', 'Chimamanda Ngozi Adichie', 'English');
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    name: database
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
      app: database
  template:
    metadata:
      name: mysql-pod
      labels:
        name: mysql-pod
        app: database
    spec:
      containers:
        - name: database
          image: mysql:8.0.32
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: secret
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-preload-data-config
